spring.application.name=moviesearch
spring.thymeleaf.cache=false
catalog.dataset.path=data/movies.json
recommendation.api.base-url=http://localhost:5000
recommendation.api.connect-timeout=2s
recommendation.api.read-timeout=15s
